// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
        // YOU CAN GET MORE DETAILS ABOUT FLR FROM:
        // - https://github.com/Fly-Mix/flr-cli
        // - https://github.com/Fly-Mix/flr-vscode-extension
        // - https://github.com/Fly-Mix/flr-as-plugin
        //
        
        // ignore: unused_import
        import 'package:flutter/widgets.dart';
        // ignore: unused_import
        import 'package:flutter/services.dart' show rootBundle;
        // ignore: unused_import
        import 'package:path/path.dart' as path;
        // ignore: unused_import
        import 'package:flutter_svg/flutter_svg.dart';
        // ignore: unused_import
        import 'package:r_dart_library/asset_svg.dart';
        
        /// This `R` class is generated and contains references to static asset resources.
        class R {
          /// package name: getx_study
          static const package = "getx_study";
        
          /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
          static const image = _R_Image();
        
          /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
          static const svg = _R_Svg();
        
          /// This `R.text` struct is generated, and contains static references to static text asset resources.
          static const text = _R_Text();
        
          /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
          static const fontFamily = _R_FontFamily();
        }
/// Asset resource’s metadata class.
      /// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
      /// - packageName：flutter_demo
      /// - assetName：assets/images/example.png
      /// - fileDirname：assets/images
      /// - fileBasename：example.png
      /// - fileBasenameNoExtension：example
      /// - fileExtname：.png
      class AssetResource {
        /// Creates an object to hold the asset resource’s metadata.
        const AssetResource(this.assetName, {this.packageName}) : assert(assetName != null);
      
        /// The name of the main asset from the set of asset resources to choose from.
        final String assetName;
      
        /// The name of the package from which the asset resource is included.
        final String? packageName;
      
        /// The name used to generate the key to obtain the asset resource. For local assets
        /// this is [assetName], and for assets from packages the [assetName] is
        /// prefixed 'packages/<package_name>/'.
        String get keyName => packageName == null ? assetName : "packages/$packageName/$assetName";
      
        /// The file basename of the asset resource.
        String get fileBasename {
          final basename = path.basename(assetName);
          return basename;
        }
      
        /// The no extension file basename of the asset resource.
        String get fileBasenameNoExtension {
          final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
          return basenameWithoutExtension;
        }
      
        /// The file extension name of the asset resource.
        String get fileExtname {
          final extension = path.extension(assetName);
          return extension;
        }
      
        /// The directory path name of the asset resource.
        String get fileDirname {
          var dirname = assetName;
          if (packageName != null) {
            final packageStr = "packages/$packageName/";
            dirname = dirname.replaceAll(packageStr, "");
          }
          final filenameStr = "$fileBasename/";
          dirname = dirname.replaceAll(filenameStr, "");
          return dirname;
        }
      }
// ignore: camel_case_types
      class _R_Image_AssetResource {
        const _R_Image_AssetResource();
      
  /// asset: assets/images/ic_eye.png
      // ignore: non_constant_identifier_names
      final ic_eye = const AssetResource("assets/images/ic_eye.png", packageName: null);
  /// asset: assets/images/ic_head.jpeg
      // ignore: non_constant_identifier_names
      final ic_head_jpeg = const AssetResource("assets/images/ic_head.jpeg", packageName: null);
  /// asset: assets/images/launchImage.png
      // ignore: non_constant_identifier_names
      final launchImage = const AssetResource("assets/images/launchImage.png", packageName: null);
  /// asset: assets/images/placeholder.png
      // ignore: non_constant_identifier_names
      final placeholder = const AssetResource("assets/images/placeholder.png", packageName: null);
  /// asset: assets/images/saber.jpg
      // ignore: non_constant_identifier_names
      final saber_jpg = const AssetResource("assets/images/saber.jpg", packageName: null);
  /// asset: assets/images/saber_logo.jpg
      // ignore: non_constant_identifier_names
      final saber_logo_jpg = const AssetResource("assets/images/saber_logo.jpg", packageName: null);
  /// asset: assets/images/season_ali_pay.jpg
      // ignore: non_constant_identifier_names
      final season_ali_pay_jpg = const AssetResource("assets/images/season_ali_pay.jpg", packageName: null);
  /// asset: assets/images/upgrade.png
      // ignore: non_constant_identifier_names
      final upgrade = const AssetResource("assets/images/upgrade.png", packageName: null);
  /// asset: assets/images/welcome_1.png
      // ignore: non_constant_identifier_names
      final welcome_1 = const AssetResource("assets/images/welcome_1.png", packageName: null);
  /// asset: assets/images/welcome_2.jpg
      // ignore: non_constant_identifier_names
      final welcome_2_jpg = const AssetResource("assets/images/welcome_2.jpg", packageName: null);
      }
// ignore: camel_case_types
    class _R_Svg_AssetResource {
      const _R_Svg_AssetResource();
    
    }
// ignore: camel_case_types
    class _R_Text_AssetResource {
      const _R_Text_AssetResource();
    
    }
/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
    // ignore: camel_case_types
    class _R_Image {
      const _R_Image();
    
      final asset = const _R_Image_AssetResource();
    
  /// asset: assets/images/ic_eye.png
      // ignore: non_constant_identifier_names
      AssetImage ic_eye() {
        return AssetImage(asset.ic_eye.keyName);
      }
  /// asset: assets/images/ic_head.jpeg
      // ignore: non_constant_identifier_names
      AssetImage ic_head_jpeg() {
        return AssetImage(asset.ic_head_jpeg.keyName);
      }
  /// asset: assets/images/launchImage.png
      // ignore: non_constant_identifier_names
      AssetImage launchImage() {
        return AssetImage(asset.launchImage.keyName);
      }
  /// asset: assets/images/placeholder.png
      // ignore: non_constant_identifier_names
      AssetImage placeholder() {
        return AssetImage(asset.placeholder.keyName);
      }
  /// asset: assets/images/saber.jpg
      // ignore: non_constant_identifier_names
      AssetImage saber_jpg() {
        return AssetImage(asset.saber_jpg.keyName);
      }
  /// asset: assets/images/saber_logo.jpg
      // ignore: non_constant_identifier_names
      AssetImage saber_logo_jpg() {
        return AssetImage(asset.saber_logo_jpg.keyName);
      }
  /// asset: assets/images/season_ali_pay.jpg
      // ignore: non_constant_identifier_names
      AssetImage season_ali_pay_jpg() {
        return AssetImage(asset.season_ali_pay_jpg.keyName);
      }
  /// asset: assets/images/upgrade.png
      // ignore: non_constant_identifier_names
      AssetImage upgrade() {
        return AssetImage(asset.upgrade.keyName);
      }
  /// asset: assets/images/welcome_1.png
      // ignore: non_constant_identifier_names
      AssetImage welcome_1() {
        return AssetImage(asset.welcome_1.keyName);
      }
  /// asset: assets/images/welcome_2.jpg
      // ignore: non_constant_identifier_names
      AssetImage welcome_2_jpg() {
        return AssetImage(asset.welcome_2_jpg.keyName);
      }
    }
/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
    // ignore: camel_case_types
    class _R_Svg {
      const _R_Svg();
    
      final asset = const _R_Svg_AssetResource();
    
    }
/// This `_R_Text` class is generated and contains references to static text asset resources.
    // ignore: camel_case_types
    class _R_Text {
      const _R_Text();
    
      final asset = const _R_Text_AssetResource();
    
    }
/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
    // ignore: camel_case_types
    class _R_FontFamily {
      const _R_FontFamily();
    
    }