import 'dart:io';

/// 资源文件自动生成脚本
///
/// 使用方式：
/// ```bash
/// dart run scripts/generate_assets.dart
/// ```
///
/// 或者在 pubspec.yaml 中添加脚本命令：
/// ```yaml
/// scripts:
///   generate: dart run scripts/generate_assets.dart
/// ```
///
/// 然后运行：
/// ```bash
/// dart run generate
/// ```
void main() {
  final projectRoot = Directory.current.path;
  final assetsDir = Directory('$projectRoot/assets/images');

  if (!assetsDir.existsSync()) {
    print('❌ assets/images 目录不存在');
    return;
  }

  final files = assetsDir
      .listSync()
      .whereType<File>()
      .where((f) => !f.path.contains('.gitkeep'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  if (files.isEmpty) {
    print('⚠️ assets/images 目录为空');
    return;
  }

  final buffer = StringBuffer();
  buffer.writeln('///This file is automatically generated. DO NOT EDIT, all your changes would be lost.');
  buffer.writeln('///Run `dart run scripts/generate_assets.dart` to update');
  buffer.writeln('class Assets {');
  buffer.writeln('  Assets._();');
  buffer.writeln();

  for (final file in files) {
    // 获取相对路径
    final relativePath = file.path.replaceFirst('$projectRoot/', '');
    // 生成变量名: assets_images_ic_eye = assets/images/ic_eye.png
    final name = _toVariableName(relativePath);
    buffer.writeln("  static const String $name = '$relativePath';");
  }

  buffer.writeln();
  buffer.writeln('}');

  // 写入文件
  final outputFile = File('$projectRoot/lib/generated/assets.dart');
  outputFile.writeAsStringSync(buffer.toString());

  print('✅ 已生成 Assets 类');
  print('   文件: ${outputFile.path}');
  print('   资源数量: ${files.length}');
}

/// 将路径转换为有效的 Dart 变量名
/// assets/images/ic_eye.png -> assetsImagesIcEye
String _toVariableName(String path) {
  // 移除扩展名
  final withoutExt = path.replaceAll(RegExp(r'\.[^.]+$'), '');
  // 移除前缀 assets/
  final afterAssets = withoutExt.replaceFirst('assets/', '');
  // 将 / 和 - 替换为 _
  final withUnderscores = afterAssets.replaceAll(RegExp(r'[/-]'), '_');
  // 按 _ 分割
  final parts = withUnderscores.split('_');
  // 驼峰命名
  final camelCase = parts.map((part) {
    if (part.isEmpty) return '';
    return part[0].toUpperCase() + part.substring(1);
  }).join('');

  final result = 'assets$camelCase';

  // 如果开头是数字，添加前缀
  if (result.isNotEmpty && RegExp(r'^[0-9]').hasMatch(result[0])) {
    return 'assets$result';
  }
  return result;
}
